### ISSUE TITLE
Only use one database container for local development

### ISSUE THREAD

**Issue by bess** [pulibrary/dpul#899]
`.lando.yml` currently configures two separate database containers:

```
name: dpul
services:
  dpul_development_db:
    type: postgres:10
    portforward: true
    creds:
      database: dpul_development
  dpul_test_db:
    type: postgres:10
    portforward: true
    creds:
      database: dpul_test
```

It would be better if there were only one database container running. However, there is something in the initializers of this project that expects the database to exist already, and this causes `rake db:create` to fail, so at the moment the databases need to be created before `rake db:create` is run. 

ACCEPTANCE CRITERIA:
- [ ] There is only one postgresql container running for local development, but dev and test are still correctly separated.
